### ISSUE TITLE
Can I use it with state?

### ISSUE THREAD

**Issue by stepanvanzuriak** [alirezavalizade/background-image-on-load#1]
For me it's not working in this way
```javascript
 <BackgroundImageOnLoad
        src={this.state.image}
        onLoadBg={() => {
          // Never prints
          console.log('LOAD')
          this.setState({
            bgLoaded: true
          })
        }}
      />
```

**Comment by alirezavalizade** [comment]
No it hasn't any problem with this way i tested now, Please make sure your image really is available! And you can get the image, Or make sure your `this.state.image` is not null or undefined.

**Comment by stepanvanzuriak** [comment]
`this.state.image` changes while app work, but yes on init is `null`

**Comment by alirezavalizade** [comment]
Oh, I got that, I will publish an update in tomorrow. Thanks
